### ISSUE TITLE
Congrats on your first repo.

### ISSUE THREAD

**Issue by kricore** [heyjoecampbell/wordpress-snippets#1]
Add a README,md file as well in order to provide documentation or instructions and get antiquated with Markdown.

**Comment by heyjoecampbell** [comment]
I thought I did - https://github.com/heyjoecampbell/wordpress-snippets/blob/master/README.md

I am doing everything via the browser:)

**Comment by kricore** [comment]
My bad. I followed the link to the file. 
Also take a look at https://css-tricks.com/snippets/wordpress/ if you haven't already discovered Chris Coyer's work.
